### ISSUE TITLE
Detach this fork from rails/country_select

### ISSUE THREAD

**Issue by scudco** [countries/country_select#197]
More housekeeping :D

I believe we should try to detach this fork from rails/country_select. It always throws me for a loop when I create PRs _in this project_ yet still have to change the upstream to this repo. Github wants to automatically set it to rails/country_select since this is a forked repo.

Some quick searching makes me think a repo admin could request detachment from the main repo via GitHub Support's Virtual Assistant. 

https://stackoverflow.com/questions/29326767/unfork-a-github-fork-without-deleting/41486339#comment116493608_29326840
https://support.github.com/request?tags=rr-forksm&q=detach+fork

**Comment by pmor** [comment]
Speaking of housekeeping, could you add me as an owner on Rubygems? My handle there is `pmor`

**Comment by pmor** [comment]
I tried a couple of weeks ago, and the support bot wasn't responding property. I'll try again.

**Comment by pmor** [comment]
Repo has been datached.
