### ISSUE TITLE
HTML attributes no longer work after upgrade to 9.0 gem

### ISSUE THREAD

**Issue by mchilson** [countries/country_select#225]
Hi,

I upgraded my country_select gem in my rails 7.1 project from 8 to 9 and now this line no longer applies the CSS style class to the dropdown:

<%= f.country_select( :country_code, priority_countries: ["US", "AU", "CA", "UK"], **{class: "login-form"}**) %>

This throws an error. 

ActiveSupport::SyntaxErrorProxy: /home/mike/rails_projects/rcsb-v2/app/views/devise/registrations/edit.html.erb:51: syntax error, unexpected ')', expecting =>
..., "UK"], {class: "login-form"}) ); @output_buffer.safe_appen...

Any ideas? I have tried many variations of applying the class to the dropdown but none of them work.

**Comment by pmor** [comment]
Try `<%= f.country_select( :country_code, { priority_countries: ["US", "AU", "CA", "UK"] }, {class: "login-form"}) %>`, I believe that should work.

**Comment by mchilson** [comment]
Thanks pmor. That worked. Sometimes you can't see the forest for the trees. :-)
